### ISSUE TITLE
Namestite da 'kazaljka' ubrzava u zavisnosti od zivota

### ISSUE THREAD

**Issue by ivan-cukic-matf** [MATF-RG17/RG056-na-zapadu-nista-novo#3]
Namestite da 'kazaljka' ubrzava u zavisnosti od toga koliko je igrac povredjen - da sto je vise igrac povredjen da mu bude teze da pogodi protivnika.

**Comment by ajvazz** [comment]
Namesteno je, s tim sto je ta promena blaga i vidi se najvise kad je igrac u opasnoj zoni. Razlog za malu razliku je to sto bi onda prvi igrac imao znatnu prednost jer prvi igra, ali namesteno je da bude optimalno.
